# permissions for end users to edit metricstargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricstarget-editor-role
rules:
- apiGroups:
  - zeroone.ai.myeongsukyoon
  resources:
  - metricstargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zeroone.ai.myeongsukyoon
  resources:
  - metricstargets/status
  verbs:
  - get
