
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - zeroone.ai.myeongsukyoon
  resources:
  - metricstargets/finalizers
  verbs:
  - update
- apiGroups:
  - zeroone.ai.myeongsukyoon
  resources:
  - metricstargets/status
  verbs:
  - get
  - patch
  - update
