apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: metrics-operator-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: app
  template:
    metadata:
      labels:
        app: nginx
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.13
          ports:
            - containerPort: 80
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 31009
  selector:
    app: nginx
    tier: app
